In [1]:
import os, os.path
import numpy as np
from time import time
import pandas as pd
import math as m
import setup_runs as sr
import importlib
import matplotlib.pyplot as plt
import itertools

WARNING: gams executable '/usr/local/bin/gams' not found.

In [62]:

#df_attribute_master_id = pd.read_csv(sr.fp_csv_attribute_master)
#pull in parameters
df_params = pd.read_csv(sr.fp_csv_parameter_ranges)
#

dict_1 = pd.read_excel(os.path.join(sr.dir_ref, "parameter_x_xl_designation", "parameter_x-xl_designation.xlsx"), sheet_name = None)
dict_2 = pd.read_excel(os.path.join(sr.dir_ref, "parameter_x_xl_designation", "parameter_x-xl_designation_carlos.xlsx"), sheet_name = None)

keys_1 = ["Agriculture", "Forestry", "Ippu", "Waste"]
keys_2 = [x for x in dict_2.keys() if x not in keys_1]

params_xl = set({})
all_params_comp = set({})

# get the 
def get_params_from_traj(params):
    substr_max = "trajmax"
    substr_min = "trajmin"
    substr_mix = "trajmix"
    substr_group = "trajgroup"
    
    checkr = [x for x in params if substr_mix in x]
    dict_out = {}
    dict_out_rev = {}
    set_out = set({})
    for param in checkr:
        if "trajgroup" in param:
            s1_rep = param.split("-")[0]
            x = param.replace(s1_rep + "-", "").replace(substr_mix + "_", "")
        else:
            x = param.replace(substr_mix + "_", "")
            
        if x not in dict_out_rev.keys():
            dict_out_rev.update({x: set({param})})
        else:
            dict_out_rev.update({x: (set({param}) | dict_out_rev[x])})
        dict_out.update({param: x})
        set_out = set_out | set({x})

    return {"dict": dict_out, "dict_rev": dict_out_rev, "set": set_out}
    
    
for k in dict_1.keys():
    if k in keys_1:
        params_xl = params_xl | set(dict_1[k][dict_1[k]["x_or_xl"] != "x"]["parameter"])

        #all parameters accounted for in df_params
        all_params_comp = all_params_comp | set(dict_1[k]["parameter"])
    else:
        params_xl = params_xl | set(dict_2[k][dict_2[k]["x_or_xl"] != "x"]["parameter"])

        #all parameters accounted for in df_params
        all_params_comp = all_params_comp | set(dict_1[k]["parameter"])

#parameters that need to be added
params_add = get_params_from_traj(list(df_params["parameter"].unique()))["set"] - all_params_comp


##  SOME FUNCTIONS

def check_param(param):
    if param in params_xl:
        out = "xl"
    else:
        out = "x"
        
    #check trajgroup
    if ("trajgroup_" in param) & ("-lhs" in param):
        out = "xl"
        
    return out

def disp_str(str_in):
    str_out = str_in.replace("_", " ").replace("-", " ")
    str_out = str_out.split(" ")
    
    s_new = ""
    for s in str_out:
        if len(s) > 1:
            s = s[0].upper() + s[1:len(s)].lower()
        else:
            s = s.upper()
        s_new = s_new + " " + s
    s_new = s_new[1:len(s_new)]
    
    return s_new



##  INITIALIZE ATTRIBUTE

fields_merge = ["parameter", "sector"]
st_tuples = [tuple(x) for x in np.array(df_params[["strategy_id", "time_series_id"]].drop_duplicates())]

#initialize the parameter attribute
df_attr_pr = df_params[fields_merge].drop_duplicates()
#grab fields with "trajmax/trajmin/trajmix"

#get string identifier
substr_max = "trajmax"
substr_min = "trajmin"
substr_mix = "trajmix"
substr_group = "trajgroup"
#get parameters that should be mixed
params_mix_loop_0 = [x for x in list(df_attr_pr["parameter"]) if ((substr_mix + "_") in x)]
#get dictionary to map to sector
dict_pml_sector = {}

df_pml_append = []

for pml in params_mix_loop_0:
    #get the sector
    sec = str(df_attr_pr[df_attr_pr["parameter"] == pml]["sector"].iloc[0])
    
    #get all parameters to drop
    params_pml_drop = [pml, pml.replace(substr_mix, substr_max), pml.replace(substr_mix, substr_min)]
    df_attr_pr = df_attr_pr[~df_attr_pr["parameter"].isin(params_pml_drop)]
     
    #check if this parameter needs to be added to xl list
    pml_add_pxl = pml.replace(substr_mix + "_", "")
    if pml_add_pxl in params_xl:
        params_xl = params_xl | set({pml_add_pxl})
    #check if group is specified
    if not substr_group in pml:
        #append to the new dataframe
        df_pml_append.append([pml, sec])

df_pml_append = pd.DataFrame(df_pml_append, columns = fields_merge)



#build new attribute table
df_attr_pr = pd.concat([df_attr_pr[~df_attr_pr["parameter"].isin(df_pml_append["parameter"])], df_pml_append[list(df_attr_pr.columns)]], axis = 0)
#add in "x/xl" designation
df_attr_pr["x_xl_designation"] = [check_param(x) for x in df_attr_pr["parameter"]]
#reorder
df_attr_pr = df_attr_pr.sort_values(by = ["sector", "parameter"]).reset_index(drop = True)
#add display string
df_attr_pr["display"] = [disp_str(x) for x in list(df_attr_pr["parameter"])]

#map of replacements for selected parameters:
dict_repl_disp = {
    "Trajgroup 1 Lhs": "Copper Heat Energy - % Towards Optimistic",
    "Trajgroup 2 Lhs": "Open Pit Mine Energy - % Towards Optimistic",
    "Trajgroup 3 Lhs": "Other Industries Heat Energy - % Towards Optimistic",
    "Trajgroup 4 Lhs": "Residential Apartment ACS Energy - % Towards Optimistic",
    "Trajgroup 5 Lhs": "Residential House ACS Energy - % Towards Optimistic",
    "Trajgroup 6 Lhs": "Private Transportation Electrification - % Towards Optimistic",
    "Trajgroup 7 Lhs": "Hydrogen Adoption in Trucks - % Towards Optimistic",
    "Trajgroup 8 Lhs": "Steel Heat Energy - % Towards Optimistic",
    "Trajgroup 9 Lhs": "Hydrogen Adoption in Aviation - % Towards Optimistic",
    "Pmr Strategy": "NDC+ Electricity Sector Actions",
    "Fp Compost": "Composting"
}

#add in trajmix displays
dict_add = dict([[x, x.replace("Trajmix ", "").replace("Pib", "PIB")] for x in df_attr_pr["display"] if "Trajmix" in x])

for k in dict_add.keys():
    dict_repl_disp.update({k: dict_add[k]})
    
df_attr_pr["display"] = df_attr_pr["display"].replace(dict_repl_disp)

df_attr_pr.to_csv(sr.fp_csv_attribute_parameters, index = None, encoding = "UTF-8")

In [44]:
k = "industry_and_mining"
if k in keys_1:
    px = set(dict_1[k][dict_1[k]["x_or_xl"] != "x"]["parameter"])
else:
    px = set(dict_2[k][dict_2[k]["x_or_xl"] != "x"]["parameter"])

In [63]:
df_comp = pd.read_csv("/Users/jsyme/Downloads/attribute_parameters_old.csv")

l = list(df_comp["display"])
l_new = []
for i in range(len(l)):
    str_cur = l[i]
    j = len(str_cur)
    
    while str_cur[j - 1] == " ":
        str_cur = str_cur[0:(j - 1)]
        j = len(str_cur)
    
    l_new.append(str_cur)

df_comp["display"] = l_new

In [64]:
df_comp["old"] = [1 for x in range(len(df_comp))]
df_comp2 = pd.merge(df_attr_pr, df_comp, how = "left", on = list(set(df_comp.columns) & set(df_attr_pr.columns)))


df_attr_pr["new"] = [1 for x in range(len(df_attr_pr))]
df_comp3 = pd.merge(df_comp, df_attr_pr, how = "left", on = list(set(df_comp.columns) & set(df_attr_pr.columns)))

In [65]:
df_comp3[df_comp3["new"] != 1.0]

,parameter,sector,x_xl_designation,display,old,new
276,iron_production,industry_and_mining,x,Iron Production,1,NaN
456,pulp_production,industry_and_mining,x,Pulp Production,1,NaN
617,steel_heat_biomass,industry_and_mining,xl,Steel Heat Biomass,1,NaN
618,steel_heat_coal,industry_and_mining,xl,Steel Heat Coal,1,NaN
619,steel_heat_coke,industry_and_mining,xl,Steel Heat Coke,1,NaN
623,steel_heat_hydrogen,industry_and_mining,xl,Steel Heat Hydrogen,1,NaN

In [66]:
df_comp2[(df_comp2["old"] != 1.0)]#.to_csv("/Users/jsyme/Desktop/tmp.csv", index = None)# & (df_comp2["sector"] == "industry_and_mining")]

,parameter,sector,x_xl_designation,display,old
0,manejo_holistico_de_gando,Analytica_agriculture,xl,Manejo Holistico De Gando,NaN
3,medida_cambio_dieta_nacional,Analytica_agriculture,xl,Medida Cambio Dieta Nacional,NaN
23,medida_algas_pardas,Analytica_forestry,xl,Medida Algas Pardas,NaN
24,medida_aumento_parques_reservas,Analytica_forestry,xl,Medida Aumento Parques Reservas,NaN
25,medida_forestacion_aumentada,Analytica_forestry,xl,Medida Forestacion Aumentada,NaN
30,medida_manejo_aumentada,Analytica_forestry,xl,Medida Manejo Aumentada,NaN
32,medida_pmr_menos_papel,Analytica_forestry,xl,Medida Pmr Menos Papel,NaN
45,fp_compost,Analytica_waste,xl,Composting,NaN
139,pmr_strategy,electricity_generation,xl,NDC+ Electricity Sector Actions,NaN
531,trajgroup_8-lhs,industry_and_mining,xl,Steel Heat Energy - % Towards Optimistic,NaN
655,residential_investment_cost_retrofit_apartment,residential,x,Residential Investment Cost Retrofit Apartment,NaN
656,residential_investment_cost_retrofit_house,residential,x,Residential Investment Cost Retrofit House,NaN
658,residential_retrofit_apartment,residential,xl,Residential Retrofit Apartment,NaN
659,residential_retrofit_energy_reduction_apartment,residential,x,Residential Retrofit Energy Reduction Apartment,NaN
660,residential_retrofit_energy_reduction_house,residential,x,Residential Retrofit Energy Reduction House,NaN
665,trajmix_residential_retrofit_house,residential,x,Residential Retrofit House,NaN
668,trajgroup_9-lhs,transport,xl,Hydrogen Adoption in Aviation - % Towards Opti...,NaN
669,transport_activity_bus,transport,x,Transport Activity Bus,NaN
670,transport_activity_private,transport,x,Transport Activity Private,NaN
671,transport_activity_taxi,transport,x,Transport Activity Taxi,NaN
672,transport_activity_truck,transport,x,Transport Activity Truck,NaN
673,transport_aviation_investment_cost_hydrogen,transport,x,Transport Aviation Investment Cost Hydrogen,NaN
674,transport_aviation_investment_cost_kerosene,transport,x,Transport Aviation Investment Cost Kerosene,NaN
691,transport_fuel_price_kerosene_aviation,transport,x,Transport Fuel Price Kerosene Aviation,NaN
692,transport_intensity_aviation_hydrogen,transport,x,Transport Intensity Aviation Hydrogen,NaN
709,transport_investment_cost_modal_split_private_...,transport,x,Transport Investment Cost Modal Split Private ...,NaN
710,transport_investment_cost_modal_split_private_...,transport,x,Transport Investment Cost Modal Split Private ...,NaN
711,transport_investment_cost_modal_split_private_...,transport,x,Transport Investment Cost Modal Split Private ...,NaN
712,transport_investment_cost_modal_split_private_...,transport,x,Transport Investment Cost Modal Split Private ...,NaN

In [32]:
f = "display"
df_comp2[f].iloc[528] == df_comp3[f].iloc[0]
print(df_comp2[f].iloc[528])
print(df_comp3[f].iloc[0])

for i in range(len(df_comp3[f].iloc[0])):
    s_old = df_comp3[f].iloc[0][i]
    s_new = df_comp2[f].iloc[528][i]
    
    print("%s:\n\t new: %s\n\t old: %s\n\n"%(i, s_new, s_old))

Copper Heat Energy - % Towards Optimistic
Copper Heat Energy - % Towards Optimistic
0:
	 new: C
	 old: C


1:
	 new: o
	 old: o


2:
	 new: p
	 old: p


3:
	 new: p
	 old: p


4:
	 new: e
	 old: e


5:
	 new: r
	 old: r


6:
	 new:
	 old:


7:
	 new: H
	 old: H


8:
	 new: e
	 old: e


9:
	 new: a
	 old: a


10:
	 new: t
	 old: t


11:
	 new:
	 old:


12:
	 new: E
	 old: E


13:
	 new: n
	 old: n


14:
	 new: e
	 old: e


15:
	 new: r
	 old: r


16:
	 new: g
	 old: g


17:
	 new: y
	 old: y


18:
	 new:
	 old:


19:
	 new: -
	 old: -


20:
	 new:
	 old:


21:
	 new: %
	 old: %


22:
	 new:
	 old:


23:
	 new: T
	 old: T


24:
	 new: o
	 old: o


25:
	 new: w
	 old: w


26:
	 new: a
	 old: a


27:
	 new: r
	 old: r


28:
	 new: d
	 old: d


29:
	 new: s
	 old: s


30:
	 new:
	 old:


31:
	 new: O
	 old: O


32:
	 new: p
	 old: p


33:
	 new: t
	 old: t


34:
	 new: i
	 old: i


35:
	 new: m
	 old: m


36:
	 new: i
	 old: i


37:
	 new: s
	 old: s


38:
	 new: t
	 old: t


39:
	 new: i
	 old: i


40:
	 new: c
	 old: c

IndexError: string index out of range

In [121]:
df_params = pd.read_csv(sr.fp_csv_parameter_ranges.replace(".csv", "_design_id-1.csv"))

arch130 = "Chile_sector_package_2021_01_30_design_id-1"
df_params_130 = sr.get_archive_run(sr.fp_csv_parameter_ranges, arch130)
#check for params that were added recently
params_newadds = set(df_params["parameter"]) - set(df_params_130["parameter"])
#check for xls that are associate with trajmix/trajgroup
params_cur = list(df_params["parameter"].unique())
param_trajs = [x for x in params_cur if substr_mix in x]
traj_xls = [x for x in params_cur if ("trajgroup" in x) and ("-lhs" in x)]

for p in list(params_xl):
    check_str = substr_mix + "_" + p
    check_list = [x for x in param_trajs if check_str in x]
    
    if len(check_list) > 0:
        pml = check_list[0]
        traj_xls = traj_xls + [pml, pml.replace(substr_mix, substr_max), pml.replace(substr_mix, substr_min)]

traj_xls = set(np.array(traj_xls).flatten())
set_params_ones = params_xl | traj_xls 
#some other parameters to add in
set_ag = [x for x in list(df_params[df_params["sector"] == "Analytica_agriculture"]["parameter"].unique()) if ("medida" in x) or ("manejo" in x)]
set_fo = [x for x in list(df_params[df_params["sector"] == "Analytica_forestry"]["parameter"].unique()) if ("medida" in x) or ("manejo" in x)]
#update set
set_params_ones = set_params_ones | set(set_ag)
set_params_ones = set_params_ones | set(set_fo)
set_params_ones = set_params_ones | set({"fp_compost", "trajmix_residential_retrofit_house"})

#loop over rows to replace with ones
new_array = np.array(df_params[["min_2050", "max_2050"]].copy())

for i in range(len(df_params)):
    p = str(df_params["parameter"].iloc[i])
    
    
    if p in set_params_ones:
        new_array[i, 0] = 1.0
        new_array[i, 1] = 1.0
    #update
    if ("trajgroup" in p) and ("-lhs" in p):
        df_params["trajgroup_no_vary_q"].iloc[i] = 1
    if p == "trajmix_residential_retrofit_house":
        print(new_array[i])
        print(i)

df_params["trajgroup_no_vary_q"] = np.array(df_params["trajgroup_no_vary_q"]).astype(int)
df_params["trajgroup_no_vary_q"] = np.array(df_params["parameter_constant_q"]).astype(int)
df_params["min_2050"] = new_array[:,0]
df_params["max_2050"] = new_array[:,1]



df_params.to_csv(sr.fp_csv_parameter_ranges.replace(".csv", "_design_0.csv"), index = None, encoding = "UTF-8")

[1. 1.]
3048
[1. 1.]
3049
[1. 1.]
3050
[1. 1.]
3051

/Users/jsyme/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [125]:
set(df_params["parameter_constant_q"].unique())

{nan, 1.0}

In [123]:
df_params[df_params["parameter"] == "trajgroup_8-lhs"]

,sector,time_series_id,strategy_id,type,parameter,normalize_group,trajgroup_no_vary_q,parameter_constant_q,min_2050,max_2050,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
2336,industry_and_mining,0,0,incertidumbre,trajgroup_8-lhs,NaN,1,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2337,industry_and_mining,0,1,incertidumbre,trajgroup_8-lhs,NaN,1,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2338,industry_and_mining,1,0,incertidumbre,trajgroup_8-lhs,NaN,1,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2339,industry_and_mining,1,1,incertidumbre,trajgroup_8-lhs,NaN,1,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0