In [1]:
import setup_runs as sr
import pandas as pd
import numpy as np
import os, os.path
import importlib
import shutil
import matplotlib.pyplot as plt

In [5]:
dir_analytica = os.path.join(os.path.dirname(sr.dir_cur), "analytica")
df_params = pd.read_csv(sr.fp_csv_parameter_ranges)
df_pp = pd.read_csv(sr.fp_csv_attribute_pyparams)

dict_read = {}
df_new = []
#files
for sec in ["forestry", "agriculture"]:
    dict_read.update({sec: {}})
    sec_up = sec.upper()
    for t in ["MMA", "Best_Science"]:
        fp_in = os.path.join(dir_analytica, sec, "parameter_ranges-" + sec_up + "-" + t + ".csv")
        df_tmp = pd.read_csv(fp_in, delimiter = ";", encoding = "Latin-1")
        dict_read[sec].update({t: df_tmp.copy()})
        df_new.append(df_tmp)
df_new = pd.concat(df_new, axis = 0)
df_new = df_new[df_new["sector"].isin(["Analytica_forestry", "Analytica_agriculture", "Analytica_all"])].reset_index(drop = True)

#update parameter names
dict_param_repl = sr.build_dict(df_pp[["pyparams_by_sector", "parameter"]])
df_new["parameter"] = df_new["parameter"].replace(dict_param_repl)
df_new["parameter"] = [x.lower().replace(" ", "_").replace("Ã±", "gn").replace("_2019", "") for x in list(df_new["parameter"])]
df_new["parameter"] = df_new["parameter"].replace({"sustitucion_y_degradacion": "sustitucion_degradacion"})

df_params_new = df_params[(~df_params["parameter"].isin(df_new["parameter"]))]
#df_params_new =

In [81]:
fields_ext = list(df_params.columns)[0:9] + ["2015", "2023", "2025", "2040", "2050"]

In [7]:
#df_params[(df_params["sector"] == "Analytica_forestry")][fields_ext]
df_new.to_csv("/Users/jsyme/Desktop/tmp_df_new_agfoall.csv", index = None, encoding = "UTF-8")

In [83]:
df_new[(df_new["sector"] == "Analytica_forestry")][fields_ext]

,sector,time_series_id,strategy_id,type,parameter,normalize_group,parameter_constant_q,min_2050,max_2050,2015,2023,2025,2040,2050
0,Analytica_forestry,1,0,accion,incendio_bosque_nativo,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
1,Analytica_forestry,1,1,accion,incendio_bosque_nativo,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
2,Analytica_forestry,1,0,accion,incendio_plantaciones_forestales,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
3,Analytica_forestry,1,1,accion,incendio_plantaciones_forestales,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
4,Analytica_forestry,1,0,incertidumbre,incertidumbre_incendio_bn,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
5,Analytica_forestry,1,1,incertidumbre,incertidumbre_incendio_bn,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
6,Analytica_forestry,1,0,incertidumbre,incertidumbre_incendio_plantaciones,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
7,Analytica_forestry,1,1,incertidumbre,incertidumbre_incendio_plantaciones,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
8,Analytica_forestry,1,0,accion,recuperacion_bn,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
9,Analytica_forestry,1,1,accion,recuperacion_bn,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
10,Analytica_forestry,1,0,accion,sustitucion_degradacion,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
11,Analytica_forestry,1,1,accion,sustitucion_degradacion,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
12,Analytica_forestry,1,0,accion,tierras_convertidas_a_bn,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
13,Analytica_forestry,1,1,accion,tierras_convertidas_a_bn,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
14,Analytica_forestry,1,0,accion,tierras_convertidas_a_plantaciones,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
15,Analytica_forestry,1,1,accion,tierras_convertidas_a_plantaciones,NaN,1.0,0.8,1.2,0.0,0.700000,0.900000,1.000000,1.000000
16,Analytica_forestry,1,0,parametro,var_demanda_legna,NaN,1.0,0.2,1.2,1.0,0.972197,0.963602,0.730396,0.743467
17,Analytica_forestry,1,1,parametro,var_demanda_legna,NaN,1.0,0.2,1.2,1.0,0.972197,0.963602,0.730396,0.743467
18,Analytica_forestry,0,0,accion,incendio_bosque_nativo,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
19,Analytica_forestry,0,1,accion,incendio_bosque_nativo,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
20,Analytica_forestry,0,0,accion,incendio_plantaciones_forestales,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
21,Analytica_forestry,0,1,accion,incendio_plantaciones_forestales,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
22,Analytica_forestry,0,0,incertidumbre,incertidumbre_incendio_bn,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
23,Analytica_forestry,0,1,incertidumbre,incertidumbre_incendio_bn,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
24,Analytica_forestry,0,0,incertidumbre,incertidumbre_incendio_plantaciones,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
25,Analytica_forestry,0,1,incertidumbre,incertidumbre_incendio_plantaciones,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
26,Analytica_forestry,0,0,accion,recuperacion_bn,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
27,Analytica_forestry,0,1,accion,recuperacion_bn,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
28,Analytica_forestry,0,0,accion,sustitucion_degradacion,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
29,Analytica_forestry,0,1,accion,sustitucion_degradacion,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
30,Analytica_forestry,0,0,accion,tierras_convertidas_a_bn,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
31,Analytica_forestry,0,1,accion,tierras_convertidas_a_bn,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
32,Analytica_forestry,0,0,accion,tierras_convertidas_a_plantaciones,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
33,Analytica_forestry,0,1,accion,tierras_convertidas_a_plantaciones,NaN,1.0,0.8,1.2,0.0,0.725000,0.925000,1.000000,1.000000
34,Analytica_forestry,0,0,parametro,var_demanda_legna,NaN,1.0,0.2,1.2,1.0,0.972197,0.963602,0.730396,0.743467
35,Analytica_forestry,0,1,parametro,var_demanda_legna,NaN,1.0,0.2,1.2,1.0,0.972197,0.963602,0.730396,0.743467

In [73]:
set_ag_new = set(df_new[df_new["sector"] == "Analytica_agriculture"]["parameter"])
set_ag_par = set(df_params[df_params["sector"] == "Analytica_agriculture"]["parameter"])
set_fo_new = set(df_new[df_new["sector"] == "Analytica_forestry"]["parameter"])
set_fo_par = set(df_params[df_params["sector"] == "Analytica_forestry"]["parameter"])

set_fo_par - set_fo_new

{'especies_exoticas', 'especies_nativas'}

In [74]:
set_ag_par - set_ag_new

set()

In [60]:
df_pp

,sector,pyparams_by_sector,parameter,ppi_overwrite_scale_factor
0,agriculture,Medida_Biodigestores,medida_biodigestores,NaN
1,agriculture,Medida_CambioDietaBovina,medida_cambio_dieta_bovina,NaN
2,agriculture,Medida_CapturaCsuelos,medida_captura_c_suelos,NaN
3,agriculture,Medida_Usoeficientefertilizante,medida_uso_eficiente_fertilizante,NaN
4,agriculture,Incertidumbre_PIB,pib,1.000000e+09
5,agriculture,Incertidumbre_Poblacion,poblacion,NaN
6,agriculture,Incertidumbre_PrecioBovino,precio_bovino,NaN
7,agriculture,Incertidumbre_PrecioCerdo,precio_cerdo,NaN
8,agriculture,Incertidumbre_PrecioLeche,precio_leche,NaN
9,agriculture,Incertidumbre_PrecioMaiz,precio_maiz,NaN
10,agriculture,Incertidumbre_PrecioPollo,precio_pollo,NaN
11,forestry,LeÃ±a Especies exÃ³ticas,especies_exoticas,NaN
12,forestry,LeÃ±a Especies nativas,especies_nativas,NaN
13,forestry,Incendio Bosque Nativo,incendio_bosque_nativo,NaN
14,forestry,Incendio Plantaciones Forestales,incendio_plantaciones_forestales,NaN
15,forestry,Incertidumbre Incendio BN,incertidumbre_incendio_bn,NaN
16,forestry,Incertidumbre Incendio Plantaciones,incertidumbre_incendio_plantaciones,NaN
17,forestry,IncertidumbrePIB,pib,1.000000e+09
18,forestry,IncertidumbrePoblacion,poblacion,NaN
19,forestry,Recuperacion_BN,recuperacion_bn,NaN
20,forestry,SustituciÃ³n y degradaciÃ³n,sustitucion_degradacion,NaN
21,forestry,Tierras convertidas a BN,tierras_convertidas_a_bn,NaN
22,forestry,Tierras convertidas a plantaciones,tierras_convertidas_a_plantaciones,NaN
23,forestry,Var Demanda LeÃ±a 2019,var_demanda_legna,NaN
24,ippu,pyparam NuevaCapRecuperacion,nueva_cap_recuperacion,NaN
25,ippu,pyparam PIB,pib,NaN
26,ippu,pyparam Poblacion,poblacion,NaN
27,ippu,pyparam PqeVehicular,pqe_vehicular,NaN
28,waste,pyparams CumplimientoMetas,cumplimiento_metas,NaN
29,waste,pyparams EfCaptura,ef_captura,NaN
30,waste,pyparams PIB,pib,NaN
31,waste,pyparams Poblacion,poblacion,NaN
32,waste,pyparams PobRural,poblacion_rural,NaN
33,waste,pyparams PobUrbana,poblacion_urbana,NaN
34,waste,pyparams PTASAntofa,ptas_antofa,NaN
35,waste,pyparams PTASBiobio,ptas_biobio,NaN
36,waste,pyparams PTASValpo,ptas_valpo,NaN
37,waste,pyparams PTASLSCoq,ptasls_coq,NaN
38,waste,pyparams RSArauc,rs_arauc,NaN
39,waste,pyparams RSAysen,rs_aysen,NaN
40,waste,pyparams RSCoq,rs_coq,NaN
41,waste,pyparams RSMagallanes,rs_magallanes,NaN
42,waste,pyparams RSTarapaca,rs_tarapaca,NaN
43,waste,pyparams RSValpo,rs_valpo,NaN

In [11]:
df_out = pd.read_csv(sr.fp_csv_output_multi_sector_analytica)

In [18]:
df_out[(df_out["master_id"].isin([3, 9])) & df_out["year"].isin([2020, 2050])][[x for x in df_out.columns if ("emissions_total" in x)]]

,ag-emissions_total-mtco2e,fo-emissions_total-mtco2e,ip-emissions_total-mtco2e,wa-emissions_total-mtco2e
113,10.935187,-63.398505,12.672972,4.583495
143,9.788488,-64.336536,9.317610,5.369350
329,10.936984,-63.583045,12.675268,4.583301
359,10.360722,-68.689379,9.216811,5.334071

In [ ]:
### df_mid = pd.read_csv(sr.fp_csv_attribute_master)

In [15]:
df_mid[(df_mid["strategy_id"] == 1) & (df_mid["design_id"] == 0) & (df_mid["future_id"] == 0)]

   master_id  design_id  time_series_id  run_id  strategy_id  future_id
3          3          0               0       3            1          0
9          9          0               1       3            1          0

In [22]:
df_mid[df_mid["time_series_id"] == 1]

    master_id  design_id  time_series_id  run_id  strategy_id  future_id
6           6          0               1       0            0          0
7           7          0               1       1            0          1
8           8          0               1       2            0          2
9           9          0               1       3            1          0
10         10          0               1       4            1          1
11         11          0               1       5            1          2
18         18          1               1       0            0          0
19         19          1               1       1            0          1
20         20          1               1       2            0          2
21         21          1               1       3            1          0
22         22          1               1       4            1          1
23         23          1               1       5            1          2

In [23]:
df_mid = pd.read_csv(sr.fp_csv_attribute_master)

In [25]:
df_an = pd.read_csv(sr.fp_csv_output_multi_sector_analytica)

In [26]:
df_an

,master_id,year,ag-aov-aplicaciÃ³n_de_urea-mtco2e,ag-aov-captura_de_c_en_suelo-mtco2e,ag-aov-fermentacion_entÃ©rica-mtco2e,ag-aov-gestiÃ³n_de_estiercol-mtco2e,ag-aov-suelos_agricolas-mtco2e,ag-emissions_total-mtco2e,fo-aov-4a_forestal-mtco2e,fo-aov-4b_cultivo-mtco2e,...,ip-aov-e_industria_electrÃ³nica-mtco2e,ip-aov-f_uso_de_productos_de_sao-mtco2e,ip-aov-g_otra_producciÃ³n_y_usos-mtco2e,ip-emissions_total-mtco2e,wa-aov-a-rsu-mtco2e,wa-aov-b-compostaje-mtco2e,wa-aov-c1-incineracion-mtco2e,wa-aov-d1-aguasdomesticas-mtco2e,wa-aov-d2-aguasindustriales-mtco2e,wa-emissions_total-mtco2e
0,0,2015,0.433016,0.0,5.277093,1.581533,3.941241,11.232883,-76.415801,1.567906,...,0.0,4.572369,0.242326,9.419853,2.809852,0.059947,0.000479,0.970802,0.031893,3.872972
1,0,2016,0.356951,0.0,5.116427,1.559046,3.916720,10.949144,-75.681598,1.549870,...,0.0,5.147181,0.272268,10.441307,2.878753,0.059947,0.000533,0.953808,0.015828,3.908870
2,0,2017,0.401220,0.0,5.083247,1.556082,3.888847,10.929395,-70.987040,1.546357,...,0.0,5.684839,0.271731,11.106175,3.039759,0.059947,0.000473,0.921799,0.015828,4.037807
3,0,2018,0.406445,0.0,5.054976,1.553479,3.879309,10.894211,-67.848356,1.546062,...,0.0,6.508804,0.276276,12.004307,3.200336,0.059947,0.000513,0.934682,0.015828,4.211307
4,0,2019,0.411450,0.0,5.030701,1.576673,3.873844,10.892668,-70.895989,1.547679,...,0.0,7.190326,0.278406,12.691493,3.370680,0.059947,0.000497,0.948863,0.015828,4.395815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7267,201,2046,0.462961,0.0,3.464880,1.360913,3.796365,9.085119,-76.470511,1.582117,...,0.0,3.783228,0.351809,11.591002,4.501302,0.105986,0.003780,1.008700,0.015828,5.635596
7268,201,2047,0.461772,0.0,3.377970,1.379411,3.802191,9.021343,-76.165596,1.580306,...,0.0,3.282017,0.354472,11.198961,4.519162,0.106872,0.004047,1.009292,0.015828,5.655201
7269,201,2048,0.460361,0.0,3.290948,1.398212,3.808295,8.957817,-75.749612,1.578296,...,0.0,2.613177,0.358260,10.642650,4.537174,0.107651,0.004332,1.009674,0.015828,5.674658
7270,201,2049,0.458730,0.0,3.204049,1.417385,3.814590,8.894755,-75.124880,1.576091,...,0.0,2.616307,0.361639,10.760186,4.555385,0.108319,0.004635,1.009849,0.015828,5.694017
7271,201,2050,0.456877,0.0,3.117499,1.436987,3.798057,8.809421,-73.930904,1.573694,...,0.0,2.621106,0.365368,10.882083,4.578673,0.108872,0.004959,1.009816,0.015828,5.718149